### ISSUE TITLE
[Bug] customStartup_* should be wrapped in a spawn block

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/F3_CA_BUB#114]
**Describe the bug**
It isn't obvious that you need to bring your own spawn block into the customStartup_* scripts, JC's mission today didn't add it.  Therefore half of the framework startup ends up waiting for the custom startup code to finish.  lmao

**To Reproduce**
1. go to CA server
2. load up `CA_CO30_JC_OpSUTTON_v3`
3. checkem

**Expected behavior**
Users can decide whether the startup code needs to be sync or async.  It's still important for the startup code to be able to be sync for certain scenarios.

**Screenshots**
lol no

**Environmental Info(please complete the following information):**
 - Main repo
 - No cdlc
 - Framework Version 1.4.1

**Additional context**
Solve this by adding in a spawn block by default, and a comment above it explaining what it's doing there.

**Comment by Joecuronium** [comment]
Question: Why not just wrap the #include itself in a spawnblock? Could prevent funny business when someone accidentally deletes a part of it.

**Comment by Bubbus** [comment]
It's still important for the startup code to be able to be sync for certain scenarios.  It *could* be in the init file, but that's a piece of framework-specific knowledge you need to have if you need to use unscheduled custom code.

I can be convinced either way as neither approach is really wrong.  To have a full discussion about it would probably take more words than it's really worth lol, maybe if we're in VC some time.
