### ISSUE TITLE
[Feature Improvement] Add fallback gearscript support to take gear-variant from side instead of faction.

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/F3_CA_BUB#129]
### Is your feature request related to a problem? Please describe.
Every now and then, new MMs delete all the default units and replace them with units from CUP, CFP etc.  This happens often enough that this is probably a common workflow, so we should support it.

### Describe the solution you'd like
If a unit is being gearscripted and its faction is not recognised via `f_fnc_factionToSideName`, gearscript should then attempt to inspect the unit's side via configuration.  Use `typeOf _unit` to get its classname, search for it within the config system and find its side.

A config lookup should be fairly performant, but if it isn't then use a hashmap to cache the result.  It won't change.

### Why is this this best way to solve the problem?
Default behaviour will remain in place so nothing will change for people who are using our intended workflow.  For people using this fairly-common alternate workflow though, it means they don't have to ask us for help and then remake all their units to be compliant with our workflow - a significant hurdle for someone who is likely to just be learning our framework.

### Additional context
🍌

**Comment by dgibso29** [comment]
I'll grab this one as well.

**Comment by Bubbus** [comment]
This is already handled via `f_fnc_getUnitConfiguredSide`.  Just tested and it works good, so closing this.
