### ISSUE TITLE
[Bug] Wound Unit / Group Modules Are Broken?

### ISSUE THREAD

**Issue by dgibso29** [Bubbus/F3_CA_BUB#132]
**Describe the bug**
The Wound Unit / Group set of modules appears to have broken. 

**To Reproduce**
1. Select one of the modules
2. Try to use it
3. No error but it also doesn't work

**Expected behavior**
They work lmao (units are wounded)

**Screenshots**

**Environmental Info(please complete the following information):**
V+,  CAFE3 1.4.2 / 1.5.0

**Additional context**
why broke tho

**Comment by Bubbus** [comment]
Fix below, tested on server:

[bugfix/wound-unit-randomly](https://github.com/CombinedArmsGaming/CAFE3/tree/bugfix/wound-unit-randomly)
