### ISSUE TITLE
[Bug] Mapmarkers reset on JIP

### ISSUE THREAD

**Issue by Joecuronium** [Bubbus/F3_CA_BUB#141]
**Describe the bug**
Custom changed group mapmarkers reset on players jipping into the mission.

**To Reproduce**
Change Group marker at mission start.
Check marker whenever a player jips into the mission.
Mapmarker resets to default.

**Expected behavior**
Mapmarker stays custom.

**Environmental Info(please complete the following information):**
Main

Framework v1.5.0

**Additional context**
This is something i just remembered noticing a few mishs back. Might be related to #140

**Comment by Bubbus** [comment]
Could not reproduce after applying fixes in this PR - potential resolution here: https://github.com/CombinedArmsGaming/CAFE3/pull/154
