### ISSUE TITLE
[Bug] ACRE not working in dead spectate

### ISSUE THREAD

**Issue by Joecuronium** [Bubbus/F3_CA_BUB#145]
**Describe the bug**
Since switching dead spectate to vanilla spectate with the respawn rework, you can no longer hear friendly comms while in dead spectate (with the exception being any radios you tuned into in unconscious spectate)
**To Reproduce**
Die in op. Spectate in respawn screen.

**Expected behavior**
Hear players lamenting your death.

**Environmental Info(please complete the following information):**
 - All
 - All
 - Framework Version v1.5.1

**Comment by Joecuronium** [comment]
ok umm, it just randomly started working again, no idea how to reproduce

**Comment by Joecuronium** [comment]
and cut out again after a minute

**Comment by Bubbus** [comment]
Potential fix here, needs testing:

[bugfix/dead-spectator-voicechat](https://github.com/CombinedArmsGaming/CAFE3/tree/bugfix/dead-spectator-voicechat)

**Comment by Joecuronium** [comment]
Potential fix was tested during mishtesting today and worked with no issues, will run the modified files tomorrow during the event to test it with larger numbers.

Especially will need to test if you can hear alive comms during dead spectate.
