### ISSUE TITLE
[Bug] lootbox_macros.cpp definitions prevents sqaudMarkers from adjusting squads with color names (sort of)

### ISSUE THREAD

**Issue by BAXENdev** [Bubbus/F3_CA_BUB#157]
[lootbox_macros.hpp](https://github.com/CombinedArmsGaming/CAFE3/blob/develop/lootbox_macros.hpp) on lines 4-8 definitions collide with squad names that use fully capitalized colors in their names inside of [squadMarkers.sqf](https://github.com/CombinedArmsGaming/CAFE3/blob/develop/configuration/squadMarkers/squadMarkers_blufor.sqf). 

For example:
In 3DEN editor, a squad is named "GREEN TEAM".
In squadMarkers.sqf, that squads definition would look like:
```
SET_SQUAD_IMPORTANT(GREEN TEAM,true);
SET_SQUAD_COLOUR(GREEN TEAM,COLOUR_GREEN);
SET_SQUAD_ICON(GREEN TEAM,ICON_MOTORINF);
```

Here, "GREEN" is caught by the "#define GREEN 20" on line 5 of lootbox_macros.hpp. 

A simple workaround is to not use all caps. So bug doesnt critically break anything. It is just a hinder on naming squads by color in all caps, which is a very niche situation.

**Comment by Bubbus** [comment]
Will be resolved by #214.
