### ISSUE TITLE
[Bug] Respawn system - interface remains on map sometimes after respawn.

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/F3_CA_BUB#158]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2836506/233807219-35ac2d95-d672-4be7-9e95-9f2258cda16f.png)
![image](https://user-images.githubusercontent.com/2836506/233807229-f41a89b9-da3f-4366-a8b5-2e25ceb2a88e.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environmental Info(please complete the following information):**
 - Repo in use
 - CDLC in use
 - Framework Version [e.g. v1.3.0]

**Additional context**

**Comment by Cre8or** [comment]
wtf.

**Comment by Bubbus** [comment]
Should be fixed in 1.6.2 cause there's no respawn map anymore.
