### ISSUE TITLE
[Feature Request]  Add traits to loadouts in the gearscript

### ISSUE THREAD

**Issue by BAXENdev** [Bubbus/F3_CA_BUB#165]
### Design Goal
The gearscript system in CAFE3 is designed to guarantee that players are given the right equipment, radio, and generate supply crates based on the gear used. It the system is wholistic in that it keeps equipment and items in a mission in sync with the player's loadouts. 

But for medic and engineer roles, it does not add the normal arma traits nor the ace traits that would come with their loadout. The method for adding a trait to a medic or engineer is separated from the gearscript system. It must be added inside of eden or zeus to a specific character. This keeps the traits from being synchronized with a player's loadout should it ever change, requiring a zeus to manually synchronize the traits to that player's new loadout.

The design goal of adding a trait attribute to the loadouts in the gearscript would be to synchronize the traits to loadouts, reducing the responsibility of a zeus and making the gearscript more wholistic in its purpose. Additionally, the design implementation will be purely additive and optional, meaning that current mission makers are not required to learn how to use this new feature.

### Problem

- In a case where a medic is given traits during missionmaking and that medic plays for the entire duration of a mission, there isn't an issue.

- In a case where a medic is given traits during missionmaking and that medic does not play for the entire duration of a mission AND another player has to swap, this is an additional task for a zeus. If the zeus remembers, good on him. If not, the new medic does not have the ability to be a full medic. And correction takes additional time. Under less than ideal circumstances, plenty of negatives that could have been resolved by the trait being assigned from the gearscript rather than eden.

- In a case where an medic swaps to a non-medical loadout and the medic trait is given during missionmaking, the medic themselves nor the mission design will suffer negatively for it. This may lead to non-mission-design effects, but none of the possible effects I can think of are negative to a players experience.

### Solution

I would like to add medic traits to the gearscript as such:
```sqf
_baseLoadout = [yada yada];
CREATE_LOADOUT(superman,_baseLoadout);

ADD_TRAIT(superman,MEDIC_TRAIT); //MEDIC_TRAIT is a macro
ADD_TRAIT(superman,ENGINEER_TRAIT);
// OR
ADD_MEDIC_TRAIT(superman);
ADD_ENGINEER_TRAIT(superman);
```

The code for applying the ace traits would likely be put in `fn_applyLoadout.sqf`. (Note, I will code this feature myself).
Pseudo Code:
```
_aceMedicalValue = ACE_MEDICAL_DYNAMIC(_gearVariant,_typeOfUnit);
_unit setVariable ["ace_medical_medicclass", _aceMedicalValue, true];
```

### Notes
- This handles niche scenarios, but the goal of this feature is to make the gearscript framework wholistic in its design to assign a player loadout. This feature would help round out the gearscript framework.
- I will code this feature myself, and with help from the team if yall would like to help.
- This feature will require extensive testing with regards to the respawn system. I haven't fully read the respawn system or how it works, but the traits must persist through respawn (without negatively affecting the codebase) for this feature to be considered complete.

Thoughts?

**Comment by dgibso29** [comment]
To your point, this is a very niche case. Gearscript is already quite complex, so any additions to need to provide significant value.

I don't feel that the existing tools to mitigate this issue are poor enough to justify adding this.

**Comment by BAXENdev** [comment]
As a note, I updated the feature request after dgibso29 commented to expand on my goal of this feature and not just based on my experience of why I wanted this feature in the first place.

**Comment by dgibso29** [comment]
The edits in the summary don't fundamentally change my viewpoint: There's not significant enough value here to justify the added complexity this would represent.

Your argument for a more holistic gearscript isn't a poor one, but it overlooks that gearscript is already the most complicated piece of configuration required for a missionmaker, and it, along with ACRE configuration, is where we spend the majority of our time providing support. Not everyone who uses the framework is technically savvy.

Given the above, any additional elements we add to it need to bring significant value. For example, ACE Gunbag support provided a much cleaner and useful way to utilize Gunbags, and simplified their use along the way. Traits, however, are already easily handled in 3DEN or via Zeus modules. Mitigation for forgetting them is trivial, and the consequence of a player incorrectly having a trait after swapping to a non-medical role mid-mission (a truly niche case) are minimal.

Finally, your note regarding additional complexity when integrating with the respawn system is apt, and another reason that the value here does not outweigh the cost.

**Comment by dgibso29** [comment]
Not selected for development.
