### ISSUE TITLE
[Feature Request] Put the default INDFOR/OPFOR players back in

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/F3_CA_BUB#193]
**Is your feature request related to a problem? Please describe.**
We changed the framework from F3_CA to expect the player side to always be BLUFOR.  This isn't always the case and sometimes there's more than one player side.

**Describe the solution you'd like**
add em guys back in there

**Why is this this best way to solve the problem?**
cause then they're there

**Additional context**
🧔‍♂️

**Comment by dgibso29** [comment]
Recommended release note: "Removed NATO bias."
