### ISSUE TITLE
[Update] Update fn_addMedsToCrate with new ACE medical item.

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/F3_CA_BUB#204]
**Is your feature request related to a problem? Please describe.**
ACE has added a new medical item (painkillers), add it to the addMedsToCrate distribution.

Also maybe take a closer look at this family of functions as it's been a long time since they were written.  Do they still make sense in <current year>?  Any new items since then that we want to include by default?  Canteens for example?  Do we want to change these functions at all?

**Describe the solution you'd like**
just did

**Why is this this best way to solve the problem?**
no pills otherwise

**Additional context**
💊

**Comment by Joecuronium** [comment]
Imo this can be closed, painkillers are now added and the only other new item is the stitching kit which is needed in the medic loadout but not in crates and falls onto the missionmakers rsponsibility. Feel free to reopen if further discussion is wanted.
