### ISSUE TITLE
[Feature Request] Change framework logi default to rearm whole weapons instead of individual magazines

### ISSUE THREAD

**Issue by Joecuronium** [Bubbus/F3_CA_BUB#237]
**Is your feature request related to a problem? Please describe.**
Default setup has ACE rearming rearming each magazine seperately, leading to very long rearm times in mechinf missions

**Describe the solution you'd like**
Change the default to rearm the whole weapon with a single action. It still takes time but not too much.

**Why is this this best way to solve the problem?**
See above.

**Comment by Bubbus** [comment]
This should have been done via #220 - confusing that it's still a problem.  Can add this into 1.8.0.

**Comment by Joecuronium** [comment]
Tell you what, i inew this was done, the mission is just running outdated framework (still on 1.6.2). Closing this.
