### ISSUE TITLE
[Bug] AI Driver - Player Unable to Become AI Commander

### ISSUE THREAD

**Issue by dgibso29** [Bubbus/F3_CA_BUB#40]
▶️ check in on the ai driver script, someone had trouble removing the driver during the joint op and iirc the "become commander" function isn't working:

**Comment by Joecuronium** [comment]
Soo, I did alot of testing with this and I am unable to replicate any issues. Maybe this can be closed @dgibso29?

**Comment by dgibso29** [comment]
Closing, unable to replicate.
