### ISSUE TITLE
[Technical Improvement] More reliable Identity system.

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/F3_CA_BUB#51]
Right now Identity uses a remoteExec call to transmit identity to clients, but this fails in JIP scenarios.  It used to work, but Identity was restricted to gearscripted units so we can have Millers.

Because this applies to units which will spawn and die fairly frequently, the JIP queue will fill up steadily with keys relating to deleted units and so cannot be used unless paired with a Deleted EH.  With that EH in place though, it is a viable solution.

Anotehr solution is to store an identity variable on each unit, and when a client JIPs in, there is a local loop which examines all existing gearscripted units and applies identities on the client-side.

**Comment by Joecuronium** [comment]
After merging #54 , this issue is fixed.
