### ISSUE TITLE
[Technical Improvement] Alter macro-toggle configuration lines.

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/F3_CA_BUB#56]
The change Cre8or made in the linked comment makes certain configuration clearer.  We should apply this change throughout any applicable config files.  

Be mindful of the existing values being potentially used by code.  Check all references to each def before removing the value from it.

_Originally posted by @Bubbus in https://github.com/Bubbus/F3_CA_BUB/pull/54#discussion_r738758999_

**Comment by Joecuronium** [comment]
After merging #57, this issue is fixed.
