### ISSUE TITLE
[Documentation] Readme Revamp

### ISSUE THREAD

**Issue by dgibso29** [Bubbus/F3_CA_BUB#67]
Fill out the top portion of the readme with useful info such as what this is, how to use it, etc.

In other words, the readme needs to explain what the framework is, how to get started with it, and where to go for help.

**Comment by Bubbus** [comment]
Is this done now?

**Comment by dgibso29** [comment]
Probably ought to mention the community and how to join it as well

**Comment by dgibso29** [comment]
I'll throw myself a task to sort it out with that type of info & get this closed.

**Comment by dgibso29** [comment]
Updated readme with mentions of and links to the community.
