### ISSUE TITLE
[Bug] JIP / Respawns Potentially Ignored By Ceasefire

### ISSUE THREAD

**Issue by dgibso29** [Bubbus/F3_CA_BUB#86]
**Describe the bug**
Ceasefire potentially broken for JIPs / Respawns. Needs to be tested.

#84 may have resolved.

**To Reproduce**
1. Enable infinite Ceasefire
2. JIP / Respawn
3. Ceasefire is not properly applied

**Expected behavior**
Ceasefire applied to JIP / Respawned players

**Screenshots**

**Environmental Info(please complete the following information):**
 - Repo: V+
 - CDLC: N/A
 - Framework Version: v1.4.0

**Additional context**
Hi Cre

**Comment by dgibso29** [comment]
@Cre8or Can this safely be closed? If so, go for it.

**Comment by Cre8or** [comment]
I don't see why not.

--

Refering to https://github.com/CombinedArmsGaming/CAFE3/pull/101
