### ISSUE TITLE
[Feature] ACE gunbag expansion/integration

### ISSUE THREAD

**Issue by Joecuronium** [Bubbus/F3_CA_BUB#97]
**Is your feature request related to a problem? Please describe.**
We cant use ACE gunbag easily.

**Describe the solution you'd like**
To use ACE gunbag easily.

**Why is this this best way to solve the problem?**
Because it works.

**Additional context**
Override ace_gunbag_fnc_hasGunbag to allow other backpacks (make user definable). Add function (or dig through ACE for existing one) to streamline process for adding stored gun.

**Comment by Joecuronium** [comment]
ace_common_fnc_getWeaponState as possible convert function for the variable

**Comment by Bubbus** [comment]
If you add a function to put a gun in the gunbag, hit me up with it and I can add a gearscript macro for it.  I figure it'd be nice to be able to define `ADD_GUN_TO_GUNBAG(mgl_guy,"weap_cool_mgl");` or similar.

**Comment by Joecuronium** [comment]
Good idea, I'll have a look at how to make this as unobstrusive as possible (the stored gun is just a variable array, but it is not in standard arsenal format which makes setting it up a bit of a pain
